from prettytable import PrettyTable

table = PrettyTable()
table.field_names = ['#', 'Pokemon Name', 'Type']
table.add_row(['001', 'Bulbasaur', 'Grass/Poison'])
table.add_row(['002', 'Ivysaur', 'Grass/Poison'])
table.add_row(['003', 'Venasaur', 'Grass/Poison'])
table.add_row(['004', 'Charmander', 'Fire'])
table.add_row(['005', 'Charmeleon', 'Fire'])
table.add_row(['006', 'Charizard', 'Fire/Flying'])
table.add_row(['007', 'Squirtle', 'Water'])
table.add_row(['008', 'Wartortle', 'Water'])
table.add_row(['009', 'Blastoise', 'Water'])
table.add_row(['010', 'Caterpie', 'Bug'])
table.add_row(['011', 'Metapod', 'Bug'])
table.add_row(['012', 'Butterfree', 'Bug/Flying'])
table.add_row(['013', 'Weedle', 'Bug/Poison'])
table.add_row(['014', 'Kakuna', 'Bug/Poison'])
table.add_row(['015', 'Beedrill', 'Bug/Poison'])
table.add_row(['016', 'Pidgey', 'Normal/Flying'])
table.add_row(['017', 'Pidgeotto', 'Normal/Flying'])
table.add_row(['018', 'Pidgeot', 'Normal/Flying'])
table.add_row(['019', 'Rattata', 'Normal'])
table.add_row(['020', 'Raticate', 'Normal'])
table.add_row(['021', 'Spearow', 'Normal/Flying'])
table.add_row(['022', 'Fearow', 'Normal/Flying'])
print(table)
